import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Package Docs',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'packages'}],
    },
  ],
};

export default sidebars;
